spring:
  application:
    name: BUMP
  config:
    import: optional:classpath:application-local.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/bump
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: false   # Disabled in production; Enable in application-local.yaml for local development
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: false   # Disabled in production; Enable in application-local.yaml for local development
